server {
    listen 80;

    default_type application/json;
    add_header X-Backend-Group gray always;

    location / {
        return 200 '{"service":"sf","backendGroup":"gray","message":"gray machine group"}';
    }
}

