server {
    listen 80;

    default_type application/json;
    add_header X-Backend-Group normal always;

    location / {
        return 200 '{"service":"sf","backendGroup":"normal","message":"normal machine group"}';
    }
}

